### ISSUE TITLE
Adjust references in spec to allow for 1 to N and 1 to 1 relationships

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/cradle#10]
In the cradle spec, we need the ability to create `1 to N` and `1 to 1` references between models.

For example, give a `User` model and a `Group` and a `Territory` model. A User has many Groups and a User has one Territory. 
```
User:
  properties:
    _id: uniqueidentifier auto unique
    deleted: boolean delete
    ...
  references:
    groups: multiple of Group
    territory: single of Territory

```

in the `references` section, we need to be able to specify:
for 1-n relationship: `property: multiple of X` where `X` is the Model
for a 1-1 relationship: `property: single of X` where `X` is the Model

The referenced Model will be required to have a unique identifier but the onus will be on the spec creator.
