### ISSUE TITLE
Support for new config

### ISSUE THREAD

**Issue by danielgary** [gatewayapps/cradle#56]
```yaml
emitterOptions:
  overwrite:
    _default: true
    Tenant: false
    User: false
loader:
  module: @gatewayapps/cradle-spec-loader
  options:
    source: ./.cradle/models/**/*.yml
emitters:
  graphql-schema:
    module: @gatewayapps/cradle-graphql-emitter
    output: '{{meta.Schema}}.{{Name}}'
    options:
      exclude:
        - Tenant
        - User.Properties.passwordHash
        - User.Operations
      overwrite:
        _default: true
        Tenant: false
    after: yarn graphql-codegen
```
